# Generated by Django 2.2.11 on 2020-07-18 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='bits_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='prd_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
