# Generated by Django 2.2.11 on 2020-07-19 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200719_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='initiatives.Initiative'),
        ),
    ]
