# Generated by Django 2.2.11 on 2020-07-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200719_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(default='default_user.png', upload_to='media/volunteer_pics'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
    ]
