# Generated by Django 2.2.11 on 2020-07-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200719_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(blank=True, default='Name', max_length=50, null=True),
        ),
    ]
