# Generated by Django 2.2.11 on 2020-07-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_visitor_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
