# Generated by Django 2.2.11 on 2020-07-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200720_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
