# Generated by Django 2.2.11 on 2020-12-31 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsender',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='contactsender',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 31, 21, 12, 50, 414691, tzinfo=utc)),
        ),
    ]
