# Generated by Django 2.2.11 on 2021-01-07 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210101_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsender',
            name='pincode',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='contactsender',
            name='type1_color',
            field=models.CharField(choices=[('Baby Pink', 'Baby Pink'), ('Aqua Green', 'Aqua Green')], default='Baby Pink', max_length=20),
        ),
        migrations.AddField(
            model_name='contactsender',
            name='type1_quant',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contactsender',
            name='type2_color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Navy Blue', 'Navy Blue')], default='White', max_length=20),
        ),
        migrations.AddField(
            model_name='contactsender',
            name='type2_quant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactsender',
            name='type2_string',
            field=models.CharField(choices=[('Strings', 'Strings'), ('Elastic', 'Elastic')], default='Strings', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 15, 59, 53, 230206, tzinfo=utc)),
        ),
    ]
