# Generated by Django 2.2.11 on 2021-01-08 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210107_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 14, 16, 50, 577796, tzinfo=utc)),
        ),
    ]
