# Generated by Django 2.2 on 2020-02-12 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Initiative', max_length=255, verbose_name='Name')),
                ('description', models.TextField(default='New Initiative Description', max_length=1000, verbose_name='Description')),
                ('date_started', models.DateField(default=datetime.datetime(2020, 2, 12, 20, 1, 24, 995281, tzinfo=utc), verbose_name='Start Date')),
                ('banner_image', models.ImageField(default='media/default.jpg', upload_to='', verbose_name='Banner Image')),
            ],
        ),
    ]
