# Generated by Django 2.2 on 2020-02-12 20:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0002_auto_20200213_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_on', models.DateField(default=datetime.datetime(2020, 2, 12, 20, 31, 39, 149966, tzinfo=utc))),
                ('message', models.TextField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='postcomments',
            name='post',
        ),
        migrations.AddField(
            model_name='initiative',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2020, 2, 12, 20, 31, 39, 120422, tzinfo=utc), verbose_name='Start Date'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostComments',
        ),
        migrations.AddField(
            model_name='initiativecomments',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Initiative'),
        ),
    ]
