# Generated by Django 2.2 on 2020-02-13 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_auto_20200213_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='fb_url',
            field=models.URLField(default='https://www.facebook.com/', max_length=255, verbose_name='Facebook Page URL'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='ig_url',
            field=models.URLField(default='https://www.instagram.com/', max_length=255, verbose_name='Instagram Page URL'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='meta_description',
            field=models.TextField(default='Text....', max_length=1000, verbose_name='Meta_Description'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 12, 41, 8, 403302, tzinfo=utc), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='initiativecomments',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='initiatives.Initiative'),
        ),
        migrations.AlterField(
            model_name='initiativecomments',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 12, 41, 8, 511579, tzinfo=utc)),
        ),
    ]
