# Generated by Django 2.2 on 2020-02-13 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_auto_20200213_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='banner_image',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 13, 0, 48, 993121, tzinfo=utc), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 13, 0, 49, 22953, tzinfo=utc)),
        ),
    ]
