# Generated by Django 2.2 on 2020-02-13 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_auto_20200213_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='banner_image',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 13, 19, 12, 934753, tzinfo=utc), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='fb_url',
            field=models.URLField(default='https://www.facebook.com/NirmaanPilaniPage/', max_length=255, verbose_name='Facebook Page URL'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='ig_url',
            field=models.URLField(default='https://www.instagram.com/nirmaan_pilani/', max_length=255, verbose_name='Instagram Page URL'),
        ),
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 13, 19, 13, 38447, tzinfo=utc)),
        ),
    ]
