# Generated by Django 2.2 on 2020-02-15 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0007_auto_20200213_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='banner_image',
            field=models.ImageField(default='default.png', upload_to='banner_images', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2020, 2, 15, 14, 9, 19, 577768, tzinfo=utc), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 2, 15, 14, 9, 19, 607208, tzinfo=utc)),
        ),
    ]
