# Generated by Django 2.2 on 2020-02-15 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0008_auto_20200215_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2020, 2, 15, 15, 14, 41, 784168, tzinfo=utc), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 2, 15, 15, 14, 41, 813439, tzinfo=utc)),
        ),
    ]
