# Generated by Django 2.2 on 2020-02-19 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0011_auto_20200216_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2020, 2, 19, 15, 15, 1, 27100, tzinfo=utc), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 2, 19, 15, 15, 1, 57157, tzinfo=utc)),
        ),
    ]
