# Generated by Django 2.2 on 2020-03-08 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0015_auto_20200220_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='ketto_url',
            field=models.URLField(default='https://www.ketto.org/', max_length=255, verbose_name='Ketto Page URL'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2020, 3, 8, 6, 27, 25, 387014, tzinfo=utc), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 3, 8, 6, 27, 25, 417416, tzinfo=utc)),
        ),
    ]
