# Generated by Django 2.2 on 2020-03-08 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0016_auto_20200308_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2020, 3, 8, 7, 1, 16, 289299, tzinfo=utc), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='initiativecomment',
            name='message',
            field=models.CharField(default='', max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 3, 8, 7, 1, 16, 320315, tzinfo=utc)),
        ),
    ]
