# Generated by Django 2.2 on 2020-03-10 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0017_auto_20200308_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2020, 3, 10, 7, 53, 20, 594254, tzinfo=utc), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 3, 10, 7, 53, 20, 625138, tzinfo=utc)),
        ),
    ]
