# Generated by Django 2.2.11 on 2020-07-18 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0024_auto_20200711_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 7, 18, 6, 34, 47, 137042, tzinfo=utc)),
        ),
    ]
