# Generated by Django 2.2.11 on 2020-07-18 20:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0025_auto_20200718_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='meta_description',
        ),
        migrations.AddField(
            model_name='initiative',
            name='slug',
            field=models.CharField(default='', max_length=255, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='volunteers_file',
            field=models.FileField(null=True, upload_to='media/volunteers_files'),
        ),
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 7, 18, 20, 46, 8, 612718, tzinfo=utc)),
        ),
    ]
