# Generated by Django 2.2.11 on 2020-07-19 05:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0026_auto_20200719_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='description',
            field=models.TextField(blank=True, default=' ', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='slug',
            field=models.CharField(default=' ', max_length=255, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 7, 19, 5, 32, 28, 11702, tzinfo=utc)),
        ),
    ]
