# Generated by Django 2.2.11 on 2020-07-19 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0027_auto_20200719_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 7, 19, 6, 25, 50, 249704, tzinfo=utc)),
        ),
    ]
