# Generated by Django 2.2.11 on 2020-07-20 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0034_auto_20200720_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2020, 7, 20, 13, 23, 59, 364768, tzinfo=utc)),
        ),
    ]
