# Generated by Django 2.2.11 on 2021-01-07 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0041_auto_20210101_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2021, 1, 7, 15, 59, 53, 225186, tzinfo=utc)),
        ),
    ]
