# Generated by Django 2.2.11 on 2021-01-08 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0042_auto_20210107_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2021, 1, 8, 14, 16, 50, 575626, tzinfo=utc)),
        ),
    ]
