# Generated by Django 2.2 on 2021-03-06 20:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0043_auto_20210108_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 20, 33, 12, 724339, tzinfo=utc)),
        ),
    ]
