# Generated by Django 3.1.7 on 2021-03-28 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0046_auto_20210328_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativecomment',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 18, 34, 3, 190558, tzinfo=utc)),
        ),
    ]
